# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-02 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('total', models.IntegerField()),
                ('user_number', models.IntegerField()),
                ('unit', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=128, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
