# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-03 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='comment',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
