# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-02 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=12)),
                ('date', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('phone', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('number', models.IntegerField()),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Fruit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
